name = "m3ugc"
main = "src/index.js"
compatibility_date = "2023-10-25"

# 定时任务：每天凌晨 3:00 (UTC) 自动抓取更新直播源
[triggers]
crons = ["*/10 * * * *"]

# KV 命名空间绑定
# 注意：部署前，请先在终端运行 `npx wrangler kv:namespace create IPTV_KV`
# 然后将生成的 id 填入下方
[[kv_namespaces]]
binding = "IPTV_KV"
id = "a089b1636c7b49d885e4ffe8dc2c4e17"

# 环境变量 (设置管理员默认账号密码，可在后台修改)
[vars]
DEFAULT_ADMIN_USER = "ikun"
DEFAULT_ADMIN_PASS = "03040404aA@"
